### ISSUE TITLE
Possibility of a PyPi package?

### ISSUE THREAD

**Issue by jayaddison** [jcranch/octrees#2]
:wave: hello - I discovered this library while looking for pure-Python octree implementations for [yesterday's advent of code puzzle](https://adventofcode.com/2021/day/22).

I wondered if you have any plans to publish the library to PyPi to make it easier to re-use?  (it's also possible I could find some time over the holidays to look into preparing packaging for it, as a pull request)

**Comment by jcranch** [comment]
Dear James,

Merry Christmas!

I've not really had much direct experience of PyPi (I tend to just use
Debian packages), so it would be a little out of my way to do it. But,
if you'd like to do it it's very likely that I'd accept such a request.

Incidentally, I did have a look at that puzzle, but I didn't see a
really intelligent octree-based algorithm (though I could see a couple
of workable non-octree-based approaches).

Cheers,

James
\/\/\

**Comment by jayaddison** [comment]
Merry Christmas to you too!

Okie doke; I'll take a look into configuring packaing, as time allows.

And yep, I didn't end up using octrees to solve the puzzle; early during exploration it felt like constructing (potentially multi-rooted) trees of cubes might be a viable path.. but I [switched course](https://github.com/jayaddison/aoc2021/blob/ff19257913f5b995c7dce742f0fbf9ac2a973cad/22/22.py) from that later on.

That said.. this was the only octree implementation I could find that doesn't require native language bindings, and I figured it could be useful for people in future, so a side-quest to look into publishing it on PyPi seemed worthwhile.
